### ISSUE TITLE
correlation between docker image an original version

### ISSUE THREAD

**Issue by costi1010** [EdoFede/123Solar-meterN-Docker#6]
Hi,

What is the correlation between your docker versions and original JL versions.
Like for ex: ver 3.5 --> 1.8.x ?

/C

**Comment by EdoFede** [comment]
Hi,
there is no direct correlation at the moment, because until recently there was an update link on Jean Marc site with the latest available version.

Since all the web-components are not installed bud just copied, I've wrote a script that check for updates and apply the latest release at every startup (or automated build).

Since Jean Marc recently have decided to close the site and transfer the project on github, I've now to rewrite part of my build and update it manually, following the releases on github.
At the moment, unfortunately, I have no time, but I plan to do soon.

**Comment by costi1010** [comment]
OK, Many Thanx for your answer  !! If versions will correlate i love it to have it in the docker. It's the best !! looking forward for when u have time to bring your new release. Let me know if there is anything i can help with my side./C

**Comment by EdoFede** [comment]
Solved the issue of updates (#5 ) with new release.

I don't think I'll make single releases following those of 123solar and meterN.
Unfortunately, due to the way the package is structured, it would become a very expensive manual job.

I'll try to keep last version updated and working on all platforms
